[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
bs58 = "0.5.1"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
solana-geyser-plugin-interface = "1.18.26"
thiserror = "2.0.12"

[lib]
crate-type = ["cdylib"]
